### PR TITLE
Setting up actions for thunk middleware branch

### PR DESCRIPTION
**Pull request by shilpan**
This seems to work on `3.0.0-rc3` but fails in `3.0.0-rc2`

### CODE REVIEW

**Comment by bdefore** [comment]
It's understandable that it would not work on 3.0.0-rc2, which was interfering with the dispatch and getState parameters. Glad to hear that's working for you.

**Comment by shilpan** [comment]
This works on this branch but it throws an error `Uncaught TypeError: customMiddleware.concat is not a function` on my project. Trying to reproduce it, but wanted to know if you were aware of this?

**Comment by bdefore** [comment]
If you're seeing that error you might be still using objects for your middleware index export. That needs to change to an array. Like here: https://github.com/bdefore/universal-redux-starter/blob/thunk-middleware/src/redux/middleware/index.js#L8-L10

This is a breaking change from before.

**Comment by shilpan** [comment]
Interesting, I did do that and it still throws that error. Could it have something to do with the configs?

**Comment by shilpan** [comment]
Yep! Probably should have this config set as default:

``` Javascript
redux: {
    /*
    // The path to the index of your Redux reducers. Required. Will be added
    // to Webpcak aliases.
    */
    reducers: sourceRoot + '/redux/modules/index.js',

    /*
    // A path to an index of middleware functions. On the serverside, these will
    // be called with the Express request and response. Optional.
    //
    // Expects: String
    */
    middleware: sourceRoot + '/redux/middleware/index.js'
  }
```

**Comment by bdefore** [comment]
Ah ha, that's probably a regression from this change in the case where there's no middleware. And that documentation needs to be updated. Thanks!
